version: "3.9"
services:
  db:
    image: postgis/postgis
    ports:
      - "54320:5432"
    environment:
      POSTGRES_PASSWORD: dev
    volumes:
      - db:/var/lib/postgresql
  test-db:
    image: postgis/postgis
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: test
volumes:
  db:
 
