[tool.poetry]
name = "cherrydb-meta"
version = "0.1.0"
description = ""
authors = ["Parker J. Rule <parker.rule@tufts.edu>"]

[tool.poetry.dependencies]
python = "^3.10"
SQLAlchemy = {extras = ["postgres"], version = "^1.4.45"}
pydantic = "^1.9.2"
GeoAlchemy2 = "^0.13.1"
psycopg2-binary = "^2.9.3"
databases = {extras = ["asyncpg"], version = "^0.6.1"}
click = "^8.1.3"
geopandas = "^0.11.1"
PyYAML = "^6.0"
us = "^2.0.2"
utm = "^0.7.0"
fastapi = "^0.89.1"
uvicorn = "^0.20.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
black = "^22.6.0"
isort = "^5.10.1"
alembic = "^1.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
