name: GerryDB metadata server tests
on: 
  push:
    branches: [dev, main]

  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    # Postgres configuration: see
    # https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers#running-jobs-in-containers
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgis/postgis
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 54321:5432

    strategy:
      matrix:
        python-version: ['3.12']
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install --all-extras

    - name: Install PostgreSQL client tools
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Install GDAL (ogr2ogr)
      run: |
        sudo apt-get update
        sudo apt-get install -y gdal-bin

    - name: Check formatting
      run: |
        poetry run black . --check
        poetry run isort . --diff

    - name: Run tests and generate coverage report
      run: |
        poetry run pytest -v --cov=./ --cov-report=xml
      env:
        GERRYDB_DATABASE_URI: postgresql://postgres:test@localhost:54321/postgres
        GERRYDB_TEST_DATABASE_URI: postgresql://postgres:test@localhost:54321/postgres

    - name: Upload coverage to Codecov
      if: >-
        (github.event_name == 'push' && github.ref == 'refs/heads/dev')
        ||
        (github.event_name == 'pull_request_target'
          && github.event.pull_request.base.ref == 'dev')
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: .
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true
